[tools]
age = "1.3.1"
bun = "latest"
go = "latest"
lua = "latest"
node = "latest"
python = "latest"
ruby = "latest"
shfmt = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "true"]
