[providers.age]
type = "age"
recipients = [
    "age1umfcz96s6pde9ry0f20vl9f0q5grkfgvz9puctlawu9pg430yflq7v784s",
    "age1f03m6xkc4lx7k84xrnzan2yd2ktsmvxc0fxuj55vap7alvzm35ks2ekfcv",
]
key_file = "~/.config/fnox/key.txt"

[secrets]
TEST_SYNC= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q2J0T2NVamY0SUkrVGJXU1luVVM2cE9HbVZKWDFUeDRvRkozMngwc1ZrCjVuTnk1Qk1nMVVocGtHaGM4dnZTeHJJcmk5T2NiV2x5aWNIUnFVajRvRkkKLT4gWDI1NTE5IEN3Y05KTTJWL3JhSllhZUNtRDlBVWZVU0VvcWc3UUNTRDZnMlFXMmE3bVkKVm1RdFNHUUpUaXpTSGtGSWFnRktjTTlpODRUOWl3aHVtbU9uQldXNi91SQotPiB0LGV7di1ncmVhc2UKbFBCaDQ2clh0cUFEMHdsSjNGY1l2QXpnOUdUVm5BTnFJY2MzQWxxbUo1TmJRcjhRbWdIL3NBdm55MUZJaGk3ZQp3d3F5WUlaV0dSYTY4MVZqMzFLcXFtMVJldXMKLS0tIDFJMUZ4TEQxenJ0ZVRQcW4vdW41djZYc0dqeDBSTUg1Ujd3akRISnorb0EKt2Ef9dPSQe33es6nuc2gK0DwI6+4ricjmfjhK6+NgDSKp11imZvE6h0nF+Bz" }
