"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1500

format = """
$os\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[os]
disabled = false
style = "white"

[os.symbols]
Macos = " "
Fedora = " "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "bold yellow"

[directory]
truncation_length = 4
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "
style = "blue"
repo_root_style = "bold blue"

[git_branch]
symbol = ""
format = "[$symbol $branch(:$remote_branch)]($style)"
style = "green"

[git_status]
format = " $ahead_behind$conflicted$modified$staged$untracked$stashed"
style = "yellow"
ignore_submodules = true
conflicted = "[=${count}](red) "
ahead = "[⇡${count}](green) "
behind = "[⇣${count}](green) "
diverged = "[⇡${ahead_count}](green) [⇣${behind_count}](green) "
modified = "[!${count}](yellow) "
staged = "[+${count}](yellow) "
untracked = "[?${count}](blue) "
stashed = "[*${count}](green) "

[fill]
symbol = "─"
style = "bright-black"

[cmd_duration]
min_time = 2000
format = " [$duration]($style)"

[time]
disabled = false
format = " [$time]($style)"
style = "bright-black"
time_format = "%H:%M:%S"

[package]
disabled = true
